name: 'acme_insurance'
version: '1.0.0'
config-version: 2

profile: 'acme_insurance-duckdb'

model-paths: ["models"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +materialized: table

seeds:
  +schema: main
  acme_insurance:
    Policy:
      +column_types:
        Policy_Number: "BIGINT"
