name: 'ops_pilot'
version: '1.0.0'
config-version: 2

profile: 'ops_pilot-duckdb'

model-paths: ['models']
macro-paths: ['macros']

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  ops_pilot:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
