version: 2
models:

### FACT ###
  - name: fct_reviews
    columns:
      - name: REVIEW_SENTIMENT
        tests:
          - accepted_values:
              arguments:
                values: ['positive', 'negative', 'neutral']
      - name: LISTING_ID
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_listings')
                field: LISTING_ID
          - relationships:
              arguments:
                to: ref('dim_listings_hosts')
                field: LISTING_ID