name: 'simple'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'simple-duckdb'

model-paths: ["models"]

models:
  +materialized: table
flags:
  require_generic_test_arguments_property: true